version: '3'

services:
  php:
    container_name: "shop-chicken_php"
    build:
      context: .
      args:
        - USER_ID=1000
        - USER=domino
      dockerfile: Dockerfile 
    volumes:
      - ./:/var/www/domino
    restart: always
    networks:
      - shop-chicken

  web:
    container_name: "shop-chicken_nginx"
    image: nginx:1.23.1-alpine
    working_dir: /var/www/shop-chicken
    volumes:
      - ./:/var/www/shop-chicken:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    restart: always
    ports:
      - "${WEB_DOCKER_PORT}:80"
    networks:
      - shop-chicken

  db:
    container_name: "shop-chicken_db"
    platform: linux/x86-64
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - ~/data/shop-chicken:/var/lib/mysql
    ports:
      - "${DB_DOCKER_PORT}:3306"
    networks:
      - shop-chicken

networks:
  shop-chicken:
    name: shop-chicken
    driver: bridge
